name: Release IRS

on:
  workflow_call:
    inputs:
      new-irs-version:
        description: 'New IRS version'
        required: true
        type: string
      previous-irs-version:
        description: 'Previous IRS version'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # make sure this workflow is executed based on updated repo state
      - name: Get updated repo state
        run: git pull

      - name: Extract changelog text
        # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGELOG<<$EOF" >> "$GITHUB_ENV"
          changes_details=$(sed -n -e "/## \[${{ inputs.new-irs-version }}\]/,/## \[/ p" CHANGELOG.md | head -n -1 | tail -n +2)
          # echo details and create blank line
          echo "$changes_details" >> "$GITHUB_ENV" && echo "" >> "$GITHUB_ENV"
          full_changelog_string="**Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ inputs.previous-irs-version }}...${{ inputs.new-irs-version }}"
          echo $full_changelog_string >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"     

      - name: Create IRS release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.CHANGELOG }}
          tag_name: ${{ inputs.new-irs-version }}

  publish-to-swaggerhub:
    name: "Publish OpenAPI spec to Swaggerhub"
    permissions:
      contents: read
    needs:
      - release
    uses: ./.github/workflows/publish-swagger-hub.yml
    with:
      version: ${{ inputs.new-irs-version }}
    secrets: inherit